# Generated by Django 2.0.1 on 2018-01-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreLearningOutcome',
            fields=[
                ('label_short', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('lower_credit_bound', models.FloatField()),
                ('upper_credit_bound', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseLearningOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.Course')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.CoreLearningOutcome')),
            ],
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('label_short', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('credits', models.FloatField()),
                ('elective_credits', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DPCourseGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField(null=True)),
                ('elective', models.BooleanField()),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.CreditType')),
            ],
        ),
        migrations.CreateModel(
            name='DPCourseSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.Course')),
                ('degree_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.DegreeProgram')),
            ],
        ),
        migrations.CreateModel(
            name='DPCourseSubstituteGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField(null=True)),
                ('elective', models.BooleanField()),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.CreditType')),
            ],
        ),
        migrations.CreateModel(
            name='DPCourseSubstituteSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.Course')),
                ('parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clo_app.DPCourseSpecific')),
            ],
        ),
    ]
