# Generated by Django 2.0.1 on 2018-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corelearningoutcome',
            name='label_short',
        ),
        migrations.AddField(
            model_name='corelearningoutcome',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='lower_credit_bound',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='upper_credit_bound',
            field=models.FloatField(null=True),
        ),
    ]
