# Generated by Django 2.0.1 on 2018-02-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clo_app', '0002_auto_20180202_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpcoursegeneric',
            name='degree_program',
            field=models.ForeignKey(default=900, on_delete=django.db.models.deletion.CASCADE, to='clo_app.DegreeProgram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dpcoursesubstitutegeneric',
            name='parent_course',
            field=models.ForeignKey(default=900, on_delete=django.db.models.deletion.CASCADE, to='clo_app.DPCourseSpecific'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clo_app.CoreLearningOutcome'),
        ),
        migrations.AlterField(
            model_name='dpcoursegeneric',
            name='credit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clo_app.CreditType'),
        ),
        migrations.AlterField(
            model_name='dpcoursesubstitutegeneric',
            name='credit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clo_app.CreditType'),
        ),
    ]
